# Generated by Django 4.1.3 on 2022-11-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='maker',
            field=models.CharField(max_length=50),
        ),
    ]
